version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: frontend
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    command: sh -c "npm install && npm run build && npm run start"
    ports:
      - 3000:3000
